#!/bin/bash

echo "🧪 SESSION PERSISTENCE TESTING GUIDE"
echo "===================================="
echo ""
echo "📋 Prerequisites:"
echo "  1. Application harus sudah running (npm run dev + php artisan serve)"
echo "  2. Open browser at http://localhost (atau sesuai APP_URL)"
echo ""
echo ""
echo "🔧 Test 1: Basic Login & Refresh"
echo "=================================="
echo "Steps:"
echo "  1. Go to /login"
echo "  2. Input valid credentials"
echo "  3. Click login"
echo "  4. Wait for redirect to /dashboard"
echo "  5. Press Ctrl+R (Windows/Linux) atau Cmd+R (Mac)"
echo "  6. ✅ Expected: Stay di dashboard, NOT redirect to login"
echo ""
echo "🔍 Verification:"
echo "  - Open DevTools (F12)"
echo "  - Go to Console tab"
echo "  - Should see: '✅ Token verified successfully'"
echo "  - Check Network tab: /api/me should return 200"
echo ""
echo ""
echo "🔧 Test 2: Check Token Storage"
echo "================================="
echo "Steps:"
echo "  1. Login successfully"
echo "  2. Open DevTools Console (F12)"
echo "  3. Paste this:"
echo ""
echo "     // Check token"
echo "     const token = localStorage.getItem('auth_token')"
echo "     console.log('Token:', token ? token.substring(0, 20) + '...' : 'NOT FOUND')"
echo ""
echo "     // Check user"
echo "     const user = JSON.parse(localStorage.getItem('user'))"
echo "     console.log('User:', user?.name || 'NOT FOUND')"
echo ""
echo "  4. ✅ Expected: Both token and user should be found"
echo ""
echo ""
echo "🔧 Test 3: Simulate Token Expiry"
echo "=================================="
echo "Steps:"
echo "  1. Login successfully"
echo "  2. Open DevTools Console"
echo "  3. Paste this to simulate token deletion:"
echo ""
echo "     localStorage.removeItem('auth_token')"
echo "     localStorage.removeItem('user')"
echo "     window.location.reload()"
echo ""
echo "  4. ✅ Expected: Should redirect to /login"
echo ""
echo ""
echo "🔧 Test 4: Multiple Tabs"
echo "========================"
echo "Steps:"
echo "  1. Login di Tab 1"
echo "  2. Open new tab (Tab 2)"
echo "  3. Go to http://localhost/dashboard di Tab 2"
echo "  4. ✅ Expected: Should load dashboard (token shared in localStorage)"
echo "  5. Refresh Tab 2 (Ctrl+R)"
echo "  6. ✅ Expected: Should still stay at dashboard"
echo ""
echo ""
echo "🔧 Test 5: Network Monitoring"
echo "=============================="
echo "Steps:"
echo "  1. Open DevTools (F12)"
echo "  2. Go to Network tab"
echo "  3. Clear console"
echo "  4. Refresh page (Ctrl+R)"
echo "  5. Look for requests:"
echo "     - ✅ GET / (status 200)"
echo "     - ✅ GET /api/me (status 200)"
echo ""
echo "  6. Click on /api/me request"
echo "  7. Go to Headers tab"
echo "  8. Look for 'Authorization: Bearer ...'"
echo "  9. ✅ Should be present"
echo ""
echo ""
echo "📊 Network Request Details"
echo "=========================="
echo "Expected request headers:"
echo "  Authorization: Bearer {token_here}"
echo "  Content-Type: application/json"
echo "  X-Requested-With: XMLHttpRequest"
echo ""
echo "Expected response (200):"
echo "  {\"user\": {\"id\": 1, \"name\": \"User\", ...}}"
echo ""
echo ""
echo "🐛 Debugging Tips"
echo "================="
echo "If tests fail, check:"
echo ""
echo "1. Check backend logs:"
echo "   tail -f storage/logs/laravel.log"
echo ""
echo "2. Check if Sanctum tokens exist:"
echo "   php artisan tinker"
echo "   > \\Laravel\\Sanctum\\PersonalAccessToken::count()"
echo "   > // Should return > 0 after login"
echo ""
echo "3. Verify Sanctum middleware in API routes:"
echo "   grep -r \"auth:sanctum\" routes/"
echo ""
echo "4. Check session config:"
echo "   grep -A 10 \"SESSION_DRIVER\" .env"
echo ""
echo ""
echo "✅ Success Indicators"
echo "===================="
echo "Session persistence is working if:"
echo "  ✓ Login → Dashboard loads successfully"
echo "  ✓ Refresh page → Still at dashboard"
echo "  ✓ Close tab & reopen → Still logged in"
echo "  ✓ New tab at /dashboard → Works without new login"
echo "  ✓ Console shows verification logs"
echo "  ✓ /api/me returns 200 status"
echo ""
